apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $IMAGE
        ports:
        - containerPort: $PORT
        resources:
          requests:
            cpu: "$CPU_REQUEST"
            memory: "$MEMORY_REQUEST"
          limits:
            cpu: "$CPU_LIMIT"
            memory: "$MEMORY_LIMIT"
